### ISSUE TITLE
ingressgateway error message

### ISSUE THREAD

**Issue by A-magic-kind** [dxcSithLord/service-mesh_deploy#3]
error message from istio-ingressgateway pod logs:
warning envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138 gRPC config for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret rejected: Failed to load certificate chain from <inline>, only P-256 ECDSA certificates are supported thread=19

Updated with new name cert in istio-system namespace
Create certificate -> Key/Value Secret
Name : a-cert
DATA:
  ca.crt - paste ca.crt BASE64 encoded content
  tls.crt - paste a-cert host name cert
  tls.key - paste a-cert host name key
  
  warning envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138 gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8443: Failed to load certificate chain from <inline>, only P-256 ECDSA certificates are supported thread=19

**Comment by iakovos-t** [comment]
Any chance this is happening to us with our certs?

https://github.com/istio/istio/issues/22530

**Comment by dxcSithLord** [comment]
The problem was identified as the certificate algorithm used.  Switched the certificate to RSA 2048 and this was resolved
