### ISSUE TITLE
Gateway Example

### ISSUE THREAD

**Issue by DXCSithlordPadawan** [dxcSithLord/service-mesh_deploy#4]
[gateway-yaml.txt](https://github.com/user-attachments/files/17256266/gateway-yaml.txt)

**Comment by iakovos-t** [comment]
Example not operating in the same way as the app so not applicable - solr deployment not HTTPS.

Please use the provided new example as template for the app (i.e. HTTPS presentation, terminated on service mesh gw and mtls internally).

**Comment by DXCSithlordPadawan** [comment]
example 2 https
[gatewayhttps.txt](https://github.com/user-attachments/files/17257222/gatewayhttps.txt)

**Comment by iakovos-t** [comment]
Similar enough, but again different use case. This is passthrough service. Try one of the AC ones please

**Comment by DXCSithlordPadawan** [comment]
Not done on that system, they have not re-deployed yet

**Comment by iakovos-t** [comment]
With the template provided I am sure you'll get it working, it will be if not identical very close I expect

**Comment by dxcSithLord** [comment]
Template files may be different depending on TLS or non-TLS passthrough, since with passthrough, URL filtering and splitting is not possible.  Issue resolved with use of RSA 2048 key
