### ISSUE TITLE
route example

### ISSUE THREAD

**Issue by DXCSithlordPadawan** [dxcSithLord/service-mesh_deploy#5]
[project-keycloak-ingress.txt](https://github.com/user-attachments/files/17256298/janus-keycloak-ingress.txt)
[route-yaml-example.txt](https://github.com/user-attachments/files/17256308/route-yaml-example.txt)

**Comment by iakovos-t** [comment]
Route largely similar with newly provided template. Example is not great as a sample due to the fact this is managed by the operator. Please use new route template which I believe is very similar if not identical to the ones available in existing scripts

**Comment by dxcSithLord** [comment]
Issue resolved with RSA 2048 based certs
