### ISSUE TITLE
istio alternative configuration

### ISSUE THREAD

**Issue by A-magic-kind** [dxcSithLord/service-mesh_deploy#6]
https://github.com/dxcSithLord/service-mesh_deploy/blob/252caf93f6d642c2fb19533f225735a2b393b82c/template_gateway_example#L16

Alternative?
The error message before the envoy config error in #3
info ads SDS: PUSH request for node:istio-ingressgateway.istio-system resource:ROOTCA

**Comment by iakovos-t** [comment]
I do not believe this to be an issue with the secret as such. I think it might be related to the actual certificate/config itself. Please see response to issue #3 . This is commonly seen when there is a misconfiguration like a missing new line between blocks in certificates. This is supported by the fact that you changed the cert to P-256 and it still not recognised as P-256? I would look at that first before we look at alternatives to this

**Comment by A-magic-kind** [comment]
ran this:
kubectl create -n istio-system secret tls helloworld-credential \
  --key=example_certs1/helloworld.example.com.key \
  --cert=example_certs1/helloworld.example.com.crt
  
  Throws error : x509: unsupported elliptic curve

**Comment by iakovos-t** [comment]
due to running out of time, alternatives at this point: 

1) Change certs to RSA2048 or
2) incorporate the chain into the cert,crt (concat) and use the regular type tls secret with the 2 options as above. Just need to make sure the blocks are separated

**Comment by A-magic-kind** [comment]
changed to rsa2048 and cert works

**Comment by A-magic-kind** [comment]
using the command generates the same secret as via GUI, but the command line complains earlier

**Comment by iakovos-t** [comment]
Can you confirm? Is this resolved now, or are you still getting a cert error please?

**Comment by A-magic-kind** [comment]
connecting - working - rsa key worked - just need to repeat for the others

**Comment by A-magic-kind** [comment]
gateway 443
virtual service -> port 80
service -> http -> port 80

**Comment by dxcSithLord** [comment]
Issue resolved - closing
